import type { Metadata } from "next";
import "./globals.css";
import ReduxProviderWrapper from "@/redux/redux-provider/reduxProviderWrapper";
import { DashboardToaster } from "@/components/ui/Toster";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`  antialiased`}
      >
        <ReduxProviderWrapper>{children}</ReduxProviderWrapper>
        <DashboardToaster />
      </body>
    </html>
  );
}
