import type { Metadata } from "next";
import { Poppins, Outfit, Roboto } from "next/font/google";
import "./globals.css";
import ReduxProviderWrapper from "@/redux/redux-provider/reduxProviderWrapper";
import { DashboardToaster } from "@/components/ui/Toster";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-outfit",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${roboto.variable} ${outfit.variable}  antialiased`}>
        <ReduxProviderWrapper>{children}</ReduxProviderWrapper>
        <DashboardToaster />
      </body>
    </html>
  );
}
